# lab 1H, Our Time
load_lab(8)
library(readr)
ctu <- read_csv("TimeUse - Ids P6 Ruiz 2022 Fall.csv")
View(ctu)
timeuse <- timeuse_format( ctu )
View(timeuse)
names(timeuse)
dim(timeuse)
histogram(~sleep, data = timeuse)
histogram(~meals, data= timeuse)
mean(~sleep, data= timeuse)
mean(~meals, data= timeuse)
mean(~homework, data= timeuse)
histogram(~homework, data= timeuse)