# Candy Data Cleaning
library(readr)
candy <- read_csv("Edwin Hui - candy - [Template] candy (1).csv (1).csv")
View(candy)
candy <- rename(candy, name = V1, chocolate = V2, fruit = V3, caramel = V4, peanut = V5, nougat = V6, rice = V7, hard = V8, bar = V9, bag_box = V10, sugar = V11, unit = V12, win = V13)
candy <- mutate(candy, chocolate = recode(chocolate, "0"="No", "1"="Yes"))
candy <- mutate(candy, fruit = recode(fruit, "0"="No", "1"="Yes"))
candy <- mutate(candy, caramel = recode(caramel, "0"="No", "1"="Yes"))
candy <- mutate(candy, peanut = recode(peanut, "0"="No", "1"="Yes"))
candy <- mutate(candy, nougat = recode(nougat, "0"="No", "1"="Yes"))
candy <- mutate(candy, rice = recode(rice, "0"="No", "1"="Yes"))
candy <- mutate(candy, hard = recode(hard, "0"="No", "1"="Yes"))
candy <- mutate(candy, bar = recode(bar, "0"="No", "1"="Yes"))
candy <- mutate(candy, bag_box = recode(bag_box, "0"="No", "1"="Yes"))
candy <- rename(candy, nuts = peanut, sugar_percent = sugar, unit_price = unit)
bargraph(~chocolate, data = candy)
histogram(~unit_price, data = candy)