#Lab 2D, Queue It Up
rap <- rep("rap", times= 30)
rock <- rep("rock", times= 47)
country <- rep("country", times= 23)
songs <- c(rock, rap, country)
songs
music_draws <- do(50) * sample(songs, size=1, replace = TRUE)
music_draws
without <- do(100) * sample(songs, size=1, replace = FALSE)
tally(~without)
sample(songs, size=101, replace= FALSE)
hand <- do(3) * sample(candies, size = 1, replace = FALSE)
set.seed(1)
draws2 <- do(10) * sample(songs, size = 2, replace = FALSE)
View(draws2)
music101 <- mutate(draws, nrap =rowSums(draws=="rap"))
draws_sub <- filter(draws2, V1 == "rap", V2 == "rap")
nrow(draws_sub)/10
set.seed(12)
draws <- do(500) * sample(songs, size = 2, replace = FALSE)
draws <- mutate(draws, nrap = rowSums(draws == "rap"))
tally(~nrap, data = draws)
histogram(~nrap, data = draws, nint = 3)
rap <- rep("rap", times= 30)
rock <- rep("rock", times= 47)
country <- rep("country", times= 23)
songs <- c(rock, rap, country)
music_draws <- do(500) * sample(songs, size=5, replace = TRUE)
View(music_draws)
muisc_drawsuf <- filter(music_draws, V1 == "rap", V2 == "rap", V3 == "rap", V4 == "rap", V5 == "rap")
View(muisc_drawsuf)
nrow(muisc_drawsuf)/10
muisc_drawsf <- mutate(music_draws, nrap = rowSums(music_draws == "rap"))
tally(~nrap, data = muisc_drawsf)
histogram(~nrap, data = muisc_drawsf, nint = 5)
music_draws <- do(500) * sample(songs, size=5, replace = FALSE)
muisc_drawsuf <- mutate(music_draws, nrap = rowSums(music_draws == "rap"))
tally(~nrap, data = muisc_drawsuf)
histogram(~nrap, data = muisc_drawsuf, nint = 5)
