# Lab 2F: The Titanic Shuffle
load_lab(14)
View(titanic)
data("titanic")
bwplot(~fare | survived, data = titanic)
favstats(~fare | survived, data = titanic)
set.seed(44)
shuffled_survivors <- do(500)*median(fare ~ shuffle(survived),data = titanic)
View(shuffled_survivors)
shuffled_survivors <- mutate(shuffled_survivors, diff = Yes-No)
head(shuffled_survivors)
histogram(~diff, data = shuffled_survivors)
shuffled_survivorsm <- do(500)*mean(fare ~ shuffle(survived),data = titanic)
View(shuffled_survivorsm)
shuffled_survivorsm <- mutate(shuffled_survivorsm, diff = Yes-No)
head(shuffled_survivors)
